name : Yo Momma
baseurl             : /blog


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      permalink: /:title

plugins:
    - jemoji
emoji:
  src: "https://github.githubassets.com/images/icons/"
